### ISSUE TITLE
Unit Test a component having fullscreen-dialog

### ISSUE THREAD

**Issue by SachinMaharana** [TeamWertarbyte/material-ui-fullscreen-dialog#1]
Hi,

 I am having issue testing a react component having a full-screen dialog.

import FullscreenDialog from 'material-ui-fullscreen-dialog'
 
```
<FullscreenDialog
  open={this.state.open}
  onRequestClose={() => this.setState({ open: false })}
  title={'Demo dialog'}
  actionButton={<FlatButton
    label='Done'
    onTouchTap={() => this.setState({ open: false })}
  />}
>

</FullscreenDialog>
```

This is the example from the documentation. Could you please shed some light on how could i test 'onRequestClose' and onTouchTap' using enzyme.When i mount it using enzyme i am not able to simulate with click. Any comment would be helpful.

**Comment by leMaik** [comment]
I'm not really sure, but maybe it's because we use `onTouchTap` internally, so maybe you need to simulate a touch instead of a click?

On the other hand: Why do you need to test whether the button works? In the example above, it _does_ work for sure, as long as React and our fullscreen component work correctly. :wink:

**Comment by leMaik** [comment]
Closing this after two months without any response.

@SachinMaharana Feel free to open a new issue or just reply if you have any further questions.
