### ISSUE TITLE
Support for v2.x.x react-transition-group

### ISSUE THREAD

**Issue by adziashvili** [TeamWertarbyte/material-ui-fullscreen-dialog#5]
Is there any plan to support latest react-transition-group?

**Comment by leMaik** [comment]
Good point, I'll update this component. Unfortunately, this will make it unusable for anyone who still uses react-transition-group@1. :confused:

**Comment by adziashvili** [comment]
Thanks. 

Looking forward to get the new version. 

I wonder what is the best way to manage such a situation and allow backward compatibility while keeping the package up to date with latest. Not an issue for me, just curious.

**Comment by leMaik** [comment]
Well, if this was a bigger project, I'd probably go with releasing the rtg@1 version with a different tag than `latest`. But since I don't expect that many updates to this library, I'll just release a new version and add a note that if you want to use rtg@1, you have to use an older version of this component.

**Comment by leMaik** [comment]
I just saw that react-transition-group v1 is a peer dependency of Material-UI v0.x as well as the upcoming Material-UI v1 (see [here](https://github.com/callemall/material-ui/blob/master/package.json#L56) and [here](https://github.com/callemall/material-ui/blob/v1-alpha/package.json#L69)).
This means that I won't add support for react-transition-group@2 unless _they_ add support for it.
